### ISSUE TITLE
ERR_CONNECTION_REFUSED at console.taubyte.com

### ISSUE THREAD

**Issue by dillfrescott** [taubyte/tau#141]
I am pretty sure its not just my connection either as i tried multiple browsers, and combinations of local networks, 5g on my phone, and curling the address with a vps server on digital ocean, all to be met with the same error. :/

**Comment by samyfodil** [comment]
Can you share more details?

**Comment by dillfrescott** [comment]
It was fixed days ago, this issue is a week old and it was down, apparently some migrations were happening someone said?

I just forgot to close the issue.
