### ISSUE TITLE
Tests being skipped because TAU_TEST_GIT_TOKEN -> TEST_GIT_TOKEN

### ISSUE THREAD

**Issue by samyfodil** [taubyte/tau#146]
During a refactor environment variable TAU_TEST_GIT_TOKEN was changed to TEST_GIT_TOKEN

Some tests were disabled because of that. A solution is to add backward compatibility here https://github.com/taubyte/tau/blob/main/libdream/helpers/variables.go#L53
meaning: I can use TAU_TEST_GIT_TOKEN or TEST_GIT_TOKEN

Once that done, re-activate all tests affected by the issue like: https://github.com/taubyte/tau/blob/main/clients/p2p/auth/client_test.go

When testing you need to use a valid github token like this:
```
TEST_GIT_TOKEN=<valid-github-token-here> go test ./... -p 1
```

Some tests will run containers, so you'll need to have docker installed
Also, I recommend running with `-p 1` as some tests are resource heavy

**Comment by vasnt** [comment]
https://github.com/taubyte/tau/blob/2366343b2c22c0da7b1a90758dfe646655b30f84/dream/helpers/variables.go#L53 

Will below change work?

GitToken = os.getenv("TAU_TEST_GIT_TOKEN") or os.getenv("TEST_GIT_TOKEN")

**Comment by vasnt** [comment]
Additionally, such Token is being fetched in other-below 2 files also, is it required to modify code there also? 
![image](https://github.com/user-attachments/assets/42e59e32-8c96-470c-9ea8-05f66a98798a)
