### ISSUE TITLE
Refactor retry logic for deployment key

### ISSUE THREAD

**Issue by samyfodil** [taubyte/tau#152]
Sometimes, a build might be triggered before the repository is registered, which mean a deployment key was added. For these reason we have a retry logic here https://github.com/taubyte/tau/blob/main/protocols/monkey/job.go#L88. Frankly, this code does not look good.

I suggest moving the check for deployment key to https://github.com/taubyte/tau/blob/main/protocols/monkey/job.go#L41, and use a helper function that will retry for a number of times till we get repo with a deployment key.

**Comment by mortum5** [comment]
How much `Attempts` and `Delay` do we need?

**Comment by samyfodil** [comment]
You can have the retry and wait as global variables

In L41 we fetch repo info. we should re-try there if no key is found. then move on with the logic.
Re-fetching in L81 is not necessary

**Comment by mohitsethia** [comment]
Hi @samyfodil , I would like to contribute to it and I have created a reusable Retry method. Is it too complex? Maybe I can simplify and only have it specific for deployment key. And for reading maxRetries & waitBeforeRetry how can we read from global variable `os.GetEnv() || default` or keep it in Monkey struct? Can you please guide me?
I have created a draft [PR](https://github.com/taubyte/tau/pull/223).
