### ISSUE TITLE
[substrate] Add ping p2p endpoint

### ISSUE THREAD

**Issue by samyfodil** [taubyte/tau#173]
Add a ping handler to 'substrate' here https://github.com/taubyte/tau/blob/e8236cd22bfb89d79a237b2d24d771e9fd1ce001/services/substrate/stream.go#L32

Example:
https://github.com/taubyte/tau/blob/e8236cd22bfb89d79a237b2d24d771e9fd1ce001/services/auth/stream.go#L13

**Comment by vasnt** [comment]
below exact code needs to be pasted at line#32 in [tau/services/substrate/stream.go](https://github.com/taubyte/tau/blob/e8236cd22bfb89d79a237b2d24d771e9fd1ce001/services/substrate/stream.go#L32) ?


```
srv.stream.Define("ping", func(context.Context, streams.Connection, command.Body) (cr.Response, error) {
		return cr.Response{"time": int(time.Now().Unix())}, nil
	})
```

**Comment by samyfodil** [comment]
@vasnt that should do
