### ISSUE TITLE
De-duplicate starfish mock client

### ISSUE THREAD

**Issue by samyfodil** [taubyte/tau#174]
`starfish` is a mock client for `patrick`. The problem is that it is defined 3 times. See:
https://github.com/taubyte/tau/blob/e8236cd22bfb89d79a237b2d24d771e9fd1ce001/services/monkey/patrick_struct_test.go#L13
https://github.com/taubyte/tau/blob/e8236cd22bfb89d79a237b2d24d771e9fd1ce001/services/monkey/tests/patrick_struct_test.go#L13
https://github.com/taubyte/tau/blob/e8236cd22bfb89d79a237b2d24d771e9fd1ce001/clients/p2p/monkey/tests/patrick_struct_test.go#L13

We need to consolidate in one place under `clients/p2p/patrick/mock`

**Comment by vasnt** [comment]
Random queries:
- How did you find/know these duplicates? 
- Do you think there are other such duplicates?

**Comment by vasnt** [comment]
So are you proposing any edit/changes in this issue#174 description? If yes, please do. 

> @vasnt I did a search after noticing we have two. because an interface is used for patrick client, we can replace it with starfish to mock it. it should be easy to move one of the files (maybe merge any method that's extra in others), then export starfish (turn it to Starfish - notice the upper case "S", that's how you do it in go). after that you just need to use Starfish in all the tests using starfish, then delete all the files for starfish that are now unused.
>

**Comment by samyfodil** [comment]
@vasnt just adding context and describing steps.

**Comment by samyfodil** [comment]
fixed #222
