### ISSUE TITLE
[auth/client] Use temporary folder in test

### ISSUE THREAD

**Issue by samyfodil** [taubyte/tau#176]
Use [os.MkdirTemp](https://pkg.go.dev/os#MkdirTemp) to create test folder in 
https://github.com/taubyte/tau/blob/main/clients/p2p/auth/inject_test.go#L17

**Comment by Qu-Ack** [comment]
do you want the temp dir in the same folder ?

**Comment by samyfodil** [comment]
@Qu-Ack [os.MkdirTemp](https://pkg.go.dev/os#MkdirTemp) will return a folder for you. It is used around in many tests, just do the same.
