### ISSUE TITLE
[cleanup] Delete deprecated DomainsWhiteList struct

### ISSUE THREAD

**Issue by samyfodil** [taubyte/tau#205]
Delete deprecated struct https://github.com/taubyte/tau/blob/f48d15e76e64065d5cacb159bd98e159205baa20/config/tau.go#L62
make sure it's not being used anywhere else.

**Comment by vasnt** [comment]
how to find whether it is used elsewhere or not?
e.g. 

- bundleorigin (2 results so it is used elsewhere)

 ![image](https://github.com/user-attachments/assets/f61f9ab8-8df9-41a2-bef9-de7bf368850e)


- domainswhitelist (1 result so it confirms not used elsewhere? )
 ![image](https://github.com/user-attachments/assets/1d49e285-7ce3-4a09-910a-62274b3e8270)


is that correct understanding? or you can advice other ways to find out usage.

**Comment by samyfodil** [comment]
@vasnt that's a good way. looks like it's not used anywhere else. So it just deleting the DomainsWhiteList struct.

**Comment by vasnt** [comment]
is there any more action needed after this step?

![image](https://github.com/user-attachments/assets/f8878152-7ff9-4e0d-b410-55323a419c18)

![image](https://github.com/user-attachments/assets/23c5cb7b-adb1-4244-9f20-91f0acf59d52)

**Comment by samyfodil** [comment]
yes, create a pull request

**Comment by vasnt** [comment]
created. next?

**Comment by samyfodil** [comment]
I'll run test and review. if all good, I'll merged it :+1:
