### ISSUE TITLE
Replace MkdirTemp calls in tests with t.TempDir()

### ISSUE THREAD

**Issue by samyfodil** [taubyte/tau#233]
Some test create temporary folders. Example: https://github.com/taubyte/tau/blob/2224d3f23b7689c81f0aec961e17ca5ffc85df7e/p2p/peer/pebble_peer_test.go#L14

Use t.TempDir() instead.

**Comment by jjjclarke** [comment]
Made these changes and testing that everything works. If all goes well, I'll submit a pull request soon.

**Comment by jjjclarke** [comment]
Talk about embarrassing! My apologies. Someone else can have a go ✋

**Comment by samyfodil** [comment]
@jjjclarke your PR https://github.com/taubyte/tau/pull/234 is almost there. 
TempDir takes no argument and returns one. check https://pkg.go.dev/testing#B.TempDir

**Comment by jjjclarke** [comment]
Changes have been made (and tested this time) and pull request has been updated.

**Comment by jjjclarke** [comment]
I’m stumped on this one. 🤷 Tests worked locally, but are no longer successful.

**Comment by samyfodil** [comment]
merged. thanks @jjjclarke
