### ISSUE TITLE
Docs: unclear inputs about local usage

### ISSUE THREAD

**Issue by a0m0rajab** [taubyte/tau#235]
Going through the [local cloud docs](https://tau.how/01-getting-started/01-local-cloud/)
the instruction was mentioning to install tau on local machine by using `npm i` the issue with this code is not allowing to run dream globally, When I used the global flag: `-g`, I could run tau but got the next message: 

```bash
dream new multiverse
Downloading dream v1.1.0...
-> downloading [========================================] 100% 0.0s
Extracting dream v1.1.0...
Binary not found. Please run the install script.
```

with this message, I could not get any information about the binary and how to use it, where to find it etc? 
some help would be appreciated. 

Related code: 
https://github.com/taubyte/tau-cli/blob/5d7b1e540fe44170e75c614beb94b3a6fa64c919/npm/index.js#L92-L96 

Seems like I needed to have tau-cli installed as well?

**Comment by samyfodil** [comment]
@a0m0rajab can you provide more info about the OS so I can reproduce.

**Comment by a0m0rajab** [comment]
@samyfodil I think I tried to use it on windows (do not remember exactly, but will try to use it again in the next few days)

**Comment by samyfodil** [comment]
@a0m0rajab were you able to reproduce the issue?

**Comment by samyfodil** [comment]
No enough details on the issue.
