### ISSUE TITLE
Suggestion Improvement 

### ISSUE THREAD

**Issue by qWeX23** [taubyte/tau#91]
Samy asked me to look over the repo and add suggestions for improvement. 

The main thing I would suggest looking into is a test suite. It looks like there are some of the files have tests, but there could be more. I think adding a testing workflow to the ci and check on PR would help accelerate development and increase quality. 

Thanks!

**Comment by samyfodil** [comment]
Improving test coverage is def an important goal for us. We're reworking some unit test utils that should accelerate that.
